version: "2"

services:
  ghost:
    image: ghost:0.11.9
    container_name: arrubiu_ghost
    restart: always
    volumes:
      - ./config.js:/var/lib/ghost/config.js
      - ./themes:/var/lib/ghost/themes
      - ./apps:/var/lib/ghost/apps
      - ../ghost-data/data:/var/lib/ghost/data
      - ../ghost-data/images:/var/lib/ghost/images
    ports:
      - "2368"
    environment:
      - VIRTUAL_HOST=arrubiu.local
      - NODE_ENV=development
